# Generated by Django 4.0.3 on 2022-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='None', max_length=50)),
                ('lname', models.CharField(default='None', max_length=50)),
                ('uname', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(default='None', max_length=50)),
                ('date', models.DateField()),
                ('phone', models.IntegerField(default=0, max_length=11)),
                ('city', models.CharField(default='None', max_length=100)),
                ('state', models.CharField(default='None', max_length=100)),
                ('symptoms', models.CharField(default='None', max_length=50)),
                ('problem_in_breif', models.CharField(default='None', max_length=1000)),
                ('bloodreport', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('healthreport', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('otherreport', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
    ]
